### ISSUE TITLE
PauseIfHittingBlock for Crystal Aura

### ISSUE THREAD

**Issue by Bubba112** [ionar2/salhack#102]
Better for citying

**Comment by r-33** [comment]
it should be by default pickaxe only aswell

**Comment by dominikaaaa** [comment]
not possible

**Comment by dominikaaaa** [comment]
why was this reopened? hitting a crystal counts as hitting a block. meaning it would pause all the time making it useless

**Comment by ionar2** [comment]
crystals are entities. Either way look how I just did it.
