### ISSUE TITLE
Stashfinder/Basefinder

### ISSUE THREAD

**Issue by THCFree** [ionar2/salhack#105]
It should walk/fly arround in mainly two modes.
 [Spiral]: It should loop arround in a efficient pattern making it bigger each time it loops.
[straight]: It should Fly/walk straight, add a option to avoid newchunks but make it so it cant loop on itself indefinitely,
add a feature that if loops on itself more than (x) times fly straight untill it finds already generated chunks and follows them.
add a autoelytrareplace too so you can let it afk flying arround.
Log coordinates of the chests/shulkers/(optional donkeys) on a file the format could be [server ip], [Time] [x,y,z] [dimension].

A friend found out that this could be the most efficient pattern for spiral mode but dont know for sure if its possible to do https://en.wikipedia.org/wiki/Hilbert_curve

**Comment by r-33** [comment]
this is cool

**Comment by Lendud** [comment]
Reading into that Hilbert curve was really interesting.

**Comment by ionar2** [comment]
I will start working on this tonight.

**Comment by r-33** [comment]
bump

**Comment by Zephyrs123** [comment]
amazing
