### ISSUE TITLE
AutoCrystal bug

### ISSUE THREAD

**Issue by BrunoDAMN** [ionar2/salhack#107]
When I am on any server practicing pvp and I try to move while I have the crystalaura activated, it does not let me move, it forces me to stay in the same place even if I try to move in addition to moving my camera to places where the crystals are not detonating.

To Reproduce
1.Example, log in 2bpvp, choose any kit and go down to fight.
2.Try to detonate crystals while trying to move anywhere. 
4. See how they make you "pop" for staying bug in one place

Expected behavior
Being able to chase someone while you explode crystals, attract someone to come closer and be able to enter the holes to detonate crystals safely

Im using future and another modules active by salhack

i cant send video so idk how can explain this.

**Comment by ionar2** [comment]
You must post a video please.

**Comment by BrunoDAMN** [comment]
ill send you by discord cz i cant up the file here

**Comment by dominikaaaa** [comment]
youtube.com :wheelchair:

**Comment by BrunoDAMN** [comment]
![2020-05-17 (4)](https://user-images.githubusercontent.com/65245374/82166538-5ce47a00-987e-11ea-912c-9c0c6d6e7cd5.png)
Fixed, put the multiplace off and the ticks in 3 (or more) and fixed.
