### ISSUE TITLE
crash when i log in to the server

### ISSUE THREAD

**Issue by amfero** [ionar2/salhack#108]
When I log on to any server Minecraft crashes

1. I Go to minecraft
2. Click on " connect to server"
3. Waiting for

I expected to log in to the server

This started happening when I upgraded the client to a 6.78 MB version

[crash-2020-05-13_09.23.10-client.txt](https://github.com/ionar2/salhack/files/4620271/crash-2020-05-13_09.23.10-client.txt)

**Comment by ionar2** [comment]
Do you have impact active?

**Comment by amfero** [comment]
yes

ср, 13 мая 2020 г., 19:06 ionar2 notifications@github.com:
