### ISSUE TITLE
Crystal aura no work :cry:

### ISSUE THREAD

**Issue by therealbruh69** [ionar2/salhack#131]
**Describe the bug**
For some reason crystal aura only places if im inside a hole, even if i wouldnt take any damage for placing the crystal, it still wouldn't place.
**To Reproduce**
no idea

**Expected behavior**
for it to place wheter im in a hole or not
**Screenshots**
i could screenshare it in vc, Yikes#7988
**Additional context**

**Comment by everything4lulz** [comment]
happens to me too

**Comment by ionar2** [comment]
Post your settings please.

**Comment by everything4lulz** [comment]
![2020-05-19_16 04 23](https://user-images.githubusercontent.com/50619485/82329767-7a365700-99ea-11ea-8519-951213aab72e.png)

**Comment by everything4lulz** [comment]
this is after i turned up maxselfdamage, still no luck.
