### ISSUE TITLE
smart placemode for crystal ?

### ISSUE THREAD

**Issue by DragonSlayerXVX** [ionar2/salhack#136]
is it possible to make a placemode that is like leg crystal that will place 1 block away from the player or just stuck the enemy surround and then place beside the player

**Comment by r-33** [comment]
what does this mean?

**Comment by r-33** [comment]
could you be a bit clearer, conscise and de

**Comment by dominikaaaa** [comment]
Someone explained it here: https://github.com/kami-blue/client/issues/835

**Comment by ionar2** [comment]
no.
