### ISSUE TITLE
LogoutSpots and DeathSpots?

### ISSUE THREAD

**Issue by NekoPvP** [ionar2/salhack#14]
Maybe add those. could be handy. And under render ofcourse

**Comment by ionar2** [comment]
This will be implemented when waypoints are added

**Comment by NekoPvP** [comment]
:DDD

**Comment by ionar2** [comment]
I have to first make a waypoint managing system, might do it today

**Comment by NekoPvP** [comment]
would be awesome!

**Comment by ionar2** [comment]
Optionally, there should also be a timer on the logout spot, with how much time passed since the logout.
