### ISSUE TITLE
a version switcher like jello for multi version support

### ISSUE THREAD

**Issue by darkx239** [ionar2/salhack#143]
Is my feature request related to a problem? no

Describe the solution you'd like
some sort of version switcher like how sigma has jello to be able to join a newer version such as 1.15.2

Describe alternatives you've considered
none

Additional context
none

**Comment by dominikaaaa** [comment]
no

**Comment by dominikaaaa** [comment]
it's too much work and would require of a rewrite of the client to run on 1.15
