### ISSUE TITLE
Game crashes when auto crystal tries to place crystals while flying

### ISSUE THREAD

**Issue by lorem-impsum** [ionar2/salhack#149]
Every time I try to crystal someone while flying with elytrafly on mode control the game crashes (happened multiple times on 9b9t if that helps).

Crash report: https://pastebin.com/EshCY3Rn

**Comment by lorem-impsum** [comment]
Apparently it's not only happening when I'm flying because now I can't use my auto crystal at all. Even when I try it on 2bpvp it crashes as soon as get close to someone. 

Also, I use impact 4.8.3 with salhack.

**Comment by lorem-impsum** [comment]
It's caused by vulnerability esp.

Temporary fix: turning vulnerability esp off.

**Comment by ionar2** [comment]
VulnerabilityESP was removed.
