### ISSUE TITLE
Change colour of highlighted keystrokes

### ISSUE THREAD

**Issue by BGP0** [ionar2/salhack#15]
![image](https://user-images.githubusercontent.com/59474088/81048530-6a7c2600-8eb4-11ea-98af-d36afcb5a0e3.png)
Would it be possible to add a feature which would let you change the colour of the highlighted keys? 
I have a large screen, and when the sun shines on it, it's almost impossible to tell which key is being pressed.

**Comment by ionar2** [comment]
Sure, this will be added under the dropdown of keystrokes
