### ISSUE TITLE
FightBot

### ISSUE THREAD

**Issue by Zephyrs123** [ionar2/salhack#151]
I think it would be a good idea of collaborating AI with a PVPBot , and it should have hack client side and a vanilla client side, meaning in hack client it should know how and when to use crystals and gapples and totems, and should do the fighting, and the vanilla client one is like the bot fighting as if it is an expert PVPer, like if you go to pvp.land server, you can fight bots with the different difficulty level, so it should fight like the expert bot there.    (This is a suggestion Only)

**Comment by dominikaaaa** [comment]
no

**Comment by dominikaaaa** [comment]
autocrystal literally already does this
