### ISSUE TITLE
Some things I think you should add to salhack :)

### ISSUE THREAD

**Issue by Frosty003** [ionar2/salhack#154]
I am a user of SalHack and I have some features that I think would be an excellent addition to the SalHack client:
1: AutoMine (You have likely heard this one before.)
2: auto bedtrap (I don't see many hacked clients with it so It would be useful)
3: Auto fish (I think this would be good because I'm too lazy to fish myself.)
I think these features would be very useful for salhack users.

**Comment by dominikaaaa** [comment]
suggest seperate stuff in seperate issues.
