### ISSUE TITLE
Future Replacement Part 1: Strafe

### ISSUE THREAD

**Issue by Tyler2b2t** [ionar2/salhack#155]
Salhack can replace Future with a few more updates. Currently, future's strafe is the standard among anarchy pvpers. While salhack has its own version of strafe, future's is always recommended to me.

The best solution is to match, or outperform future's strafe. In future, step cannot be used alongside strafe; If it is possible to run sprint, strafe, and step at the same time, it is still desirable to strafe WITHOUT step. The best method I have found to switch strafe modes and preserve the ability to turn speed completely off is to actually have a bind in the drop down menu for switching modes; one bind for speed itself and one to toggle between strafe and step-strafe. 

I thought about avoiding switching strafe modes with a bind in the drop down menu by having two independent modules like autotrap and autotrapfeet, creating speed(strafe) and step strafe, but the transition between binds is too inefficient. It might also be useful to have different methods of strafing to determine the best one or if there is any use for multiple logic modes.

There is only one small technical issue I have noticed with using future's strafe alongside salhack; future's strafe cannot be used with salhack's sprint, so future's sprint must be used instead. Other than that, matching future's strafe with salhack doesn't effect pvp much but serves to make salhack the next client to beat. Good luck!

**Comment by ionar2** [comment]
Can this be closed as of yesterday?
