### ISSUE TITLE
Future Replacement Part 5: Conclusion

### ISSUE THREAD

**Issue by Tyler2b2t** [ionar2/salhack#163]
Salhack can replace future in a few more updates! There are only a few modules that are worth using instead of salhack's. Some of these modules are equivalent or superior, but have not reached widespread use. These modules include speed, bow-spam, esp, name-tags, scaffold, and auto-reconnect. For example, salhack's speed may be just as good as future's, but people still use future's instead. Salhack is updated very often, while future is unlikely to see any changes that effect usability.

Matching or surpassing some of future's modules may be quite challenging, as may be the case for scaffold, name-tags, and esp. These modules are what set future apart from every other client; their quality has not been matched by anyone else since. However, with these modules, salhack will cover every mod I and others I know use, making future obsolete. Salhack is an innovative client that includes all of the new tricks, and has a lot of potential! Cheers!

Another note: In the current version, users cannot place blocks with aura or crystal aura active.

**Comment by dominikaaaa** [comment]
make a seperate issue for bug reports
