### ISSUE TITLE
i need help with stash logger

### ISSUE THREAD

**Issue by IdidntHackFortnite** [ionar2/salhack#164]
when i press stashlogger it says it creates a file but when i go to the StashFinder folder in Salhack i dont find anything could anyone tell me how to fix?

**Comment by dominikaaaa** [comment]
it saves on client close probably

**Comment by IdidntHackFortnite** [comment]
> it saves on client close probably

no it didnt save when i closed client?

**Comment by Artamedes** [comment]
just why don't you follow the issue template and properly name your issues? can't you atleast put some effort in :L

**Comment by ionar2** [comment]
It makes a file when it writes something.
