### ISSUE TITLE
Have Stashlogger turn on when Stashfinder is on

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#168]
I found out the hard way that the stashfinder doesn't log coordinates. 

If stashlogger would turn on automatically when the stashfinder was enabled that would make things easier aswell as not waste careless people (like me)'s time. Complete integration isn't really nessicary Imo, I think they work fine as separate modules just things like this are kinda annoying.

I also cant see why this would be a bad thing...

**Comment by dominikaaaa** [comment]
I don't see why they're seperate modules tbh
