### ISSUE TITLE
PvP Info

### ISSUE THREAD

**Issue by Tyler2b2t** [ionar2/salhack#173]
Salhack's arraylist only snaps to corners, and with a large screen, it can be distracting to check if the most important modules are on or off. The pvp info tries to solve this problem, but it does not include 2/4 of the most used pvp modules: speed and autotrap. 

PvPInfo should have KillAura (KA), CrystalAura (CA), AutoTrap (AT), and Speed (S). With SwordGap, and the rest of the AutoTotem options, users don't really have any reason to toggle it on/off in a pvp situation. AutoTotem should be replaced by AutoTrap as AT because it is toggled on/off quite frequently in pvp. Thanks again!

**Comment by TerikKek** [comment]
middleclick the module in hud editor that makes it not lock onto anything

**Comment by dominikaaaa** [comment]
already added, #2
