### ISSUE TITLE
Offhand crystal 

### ISSUE THREAD

**Issue by freddiethemadlad** [ionar2/salhack#178]
Basically when I enable offhand crystal it works fine...however it’s really annoying as when it goes below specific health it goes back to totem but if it goes back above the specified health you need to manually enable. I would rather that it doesn’t turn off but rather goes just to totem when you go below specifics health so you do not need to enable it again.

**Comment by Hoodlands** [comment]
...

**Comment by very-cashmoney** [comment]
use the option in auto totem

**Comment by ionar2** [comment]
I don't understand your issue.
