### ISSUE TITLE
Make aimbot a feature that doesn't toggle on when ka or ca is turned on

### ISSUE THREAD

**Issue by KatieLAZ** [ionar2/salhack#179]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dominikaaaa** [comment]
fill out the template, it isn't clear what you're asking

**Comment by ionar2** [comment]
If aimbot was not turned on for either, they both wouldn't work as you wouldn't be sending custom rotation packets..
