### ISSUE TITLE
Bairtone Like Pathfinder Compatible with Elytra

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#181]
self explanatory. I think almost anyone will find a use for this on a day to day basis. It should be designed for use on 2b. Things are kind of up in the air since the patch so maybe this could be something that is revisited a bit later.

side note: so im pretty sure baritone was named after FitMC so a salhack pathfinder would be kinda funny

**Comment by dominikaaaa** [comment]
This is extremely hard to implement, as discussed in https://github.com/kami-blue/tenor/issues/2 and https://github.com/cabaletta/baritone/issues/223

**Comment by dominikaaaa** [comment]
Ionar can reopen this if he feels like it, but I've started working on this before and it's a LOT of work.
