### ISSUE TITLE
Why am I banned on SalHack discord?

### ISSUE THREAD

**Issue by Gopro336** [ionar2/salhack#186]
I hit my 100 discord server limit and temporarily left SalHack discord to make room. When I tried to come back I'm banned apparently. The whole you leave= ban policy is weird af

**Comment by dominikaaaa** [comment]
who knows

**Comment by Gopro336** [comment]
can you add me back, Im one of the biggest error reporters/ supporters of the project

**Comment by ionar2** [comment]
We don't do unbans, join on another discord account.
