### ISSUE TITLE
AutoSign

### ISSUE THREAD

**Issue by Lawtrohux** [ionar2/salhack#187]
Multiple Groups have rewards available for doing tasks, one of these include placing signs advertising recruitment for these groups. AutoSign would be quite convenient to be able to place signs with a set text which would save having to type hundreds of signs across spawn.

I would like to have the AutoSign module available as it would save time and I believe would be a well used module.

Other clients AutoSigns usually do not work due to the laggy nature of 2b2t.

**Comment by ionar2** [comment]
3003df3dc0e491b06de3b95d858c49bb6a929167
