### ISSUE TITLE
Game crashes when I use future crystal aura

### ISSUE THREAD

**Issue by p92q** [ionar2/salhack#189]
Whenever I use future ca in the new update it crashes my game as soon as it gets near someone

**Comment by dominikaaaa** [comment]
fill out the template

**Comment by p92q** [comment]
?

**Comment by dominikaaaa** [comment]
fill out the template

**Comment by p92q** [comment]
do i put the crash report there?

**Comment by dominikaaaa** [comment]
Just fill out the entire issue template

**Comment by p92q** [comment]
ok i di it
