### ISSUE TITLE
 AntiSurround

### ISSUE THREAD

**Issue by very-cashmoney** [ionar2/salhack#191]
**Is your feature request related to a problem? Please describe.**
yes, pvping against somebody that hole camps w/ surround is annoying 

**Describe the solution you'd like**
A new module / option for autocrystal thats named

**Describe alternatives you've considered**
AntiSurround places a crystal / other block where you break a block in your opponents hole. This is to prevent them for camping w/ surround
**Additional context**
no

**Comment by ionar2** [comment]
no., place crystals manually
