### ISSUE TITLE
Anti Hunger Elytra Glitch

### ISSUE THREAD

**Issue by FastMAtt29** [ionar2/salhack#195]
**Describe the bug**
When you use sal anti-hunger you can not open elytra it just glitches out when you try

**To Reproduce**
1. Go to 'anti-hunger turn it on'
2. Click on 'turn on'

**Expected behavior**
When you press space the elytra wings should open they bug out and do not

**Screenshots**
If applicable, add screenshots to help explain your problem. N/A

**Additional context**
Add any other context about the problem here. N/A

**Comment by dominikaaaa** [comment]
This is intentional, because AntiHunger sends onGround packets to say the player is on the ground to prevent losing hunger

**Comment by dominikaaaa** [comment]
You'll also notice a similar issue with NoFall, because NoFall tells the server "hey, I didn't fall", meaning you can't open your wings

**Comment by ionar2** [comment]
don't use antihunger if you're established.
