### ISSUE TITLE
AutoTrapFeet bug

### ISSUE THREAD

**Issue by very-cashmoney** [ionar2/salhack#198]
[Repost, old one was labeled wrong]
**Describe the bug**
when your enemy is already in a hole, AutoTrapFeet wont fully trap them

**To Reproduce**
1. have your enemy on a hole
2. Activate AutoTrapFeet
3. AutoTrapFeet wont fully trap them

**Expected behavior**
it should also trap the head of the opponent because so you dont have to bind both

**Screenshots**
r
![2020-05-22_22 28 00](https://user-images.githubusercontent.com/65657161/82746215-8ef84f00-9d4a-11ea-9fdc-49d867ab54b0.png)
![2020-05-22_22 28 05](https://user-images.githubusercontent.com/65657161/82746216-90297c00-9d4a-11ea-94e7-3f327753cdaa.png)
![2020-05-22_22 28 22](https://user-images.githubusercontent.com/65657161/82746217-928bd600-9d4a-11ea-9d43-0300526fd5d3.png)

**Additional context**
no

**Comment by ionar2** [comment]
Can't reproduce
