### ISSUE TITLE
AutoTotem offhand

### ISSUE THREAD

**Issue by very-cashmoney** [ionar2/salhack#199]
**Describe the bug**
AutoTotem takes from your hotbar
**To Reproduce**
1. Go to AutoTotem
2. Mode : Crystal
3. Activate SwordGap
4. Sword in hand
5. Error

**Expected behavior**
Should take from inventory, it takes from your hotbar

**Comment by Artamedes** [comment]
https://github.com/ionar2/salhack/commit/65de7263f222014d8a4595bcf5525abc458df411
