### ISSUE TITLE
Baritone breaks ESP colors in Salhack

### ISSUE THREAD

**Issue by EmrysLe** [ionar2/salhack#200]
**What mod?**
A clear and concise description of what module it is.
ESP colors, ie hole esp, CA render, block highlight, etc
**Logs**
Please add logs or your issue will be closed.

**Additional context**
I was using baritone-forge-api
[2020-05-20-1.log.gz](https://github.com/ionar2/salhack/files/4673255/2020-05-20-1.log.gz)

**Comment by very-cashmoney** [comment]
???

**Comment by Lendud** [comment]
#197 
It has been fixed in 2.04
