### ISSUE TITLE
Inventory preview settings don't fully save

### ISSUE THREAD

**Issue by LiTTLEUNMAN** [ionar2/salhack#204]
**Describe the bug**
The inventory preview settings "show xcarry" and "show hotbar" don't save when the game closes.

**To Reproduce**
1. Turn on show hotbar and turn off show xcarry
2. Exit game and relaunch
3. Inventory preview has reverted back to how it was before step 1 with show hotbar off and show xcarry on.

**Expected behavior**
Expected for the settings to save and be the same after relaunching

I'm fairly sure nobody else has created an issue for this, it also happens on every version including the most recent ones.

**Comment by very-cashmoney** [comment]
use old version new one very {VERY} bug

**Comment by ionar2** [comment]
> use old version new one very {VERY} bug

You can make issues or contribute fixes yourself.
