### ISSUE TITLE
AutoTotem

### ISSUE THREAD

**Issue by Tyler2b2t** [ionar2/salhack#205]
When I am using offhand crystal and have crystals in my hotbar, the autototem will swap the totem properly when it turns on, but when it turns off it uses the crystals in my hotbar, instead of the ones in my main inventory. Unless I have hotbarcache on to reverse it, I will end up with a totem in my inventory.

I think it should prioritize the main inventory instead of the hotbar for moving items. I noticed the sword gap used to behave this way, and it now has the exact same issue of taking from the hotbar instead of the main inventory if it has the option. Thanks!

**Comment by Tyler2b2t** [comment]
I think in the new version the swordgap behaves differently than previous versions and moves the gaps in hotbar instead of the main inventory as i said before.

**Comment by EmrysLe** [comment]
I literally reported this exact issue (about the items going into main inventory and not hotbar) and he fixed it and made it like this.

Why would you want the items to not go into your hotbar?? For example when I use offhand gap, the gaps go back into my main inventory and I have to manually move it back to the hotbar if I want to eat it normally...

**Comment by Tyler2b2t** [comment]
thats because you are only carrying one stack of gaps. I am asking to prioritize the main inventory, so if you only had them in your hotbar it would use your hotbar. using the hotbar by default is ABSOLUTELY RETARDED; it completely fucks up everything else idk what the fuck you are thinking @EmrysLe

**Comment by very-cashmoney** [comment]
already reported

**Comment by Artamedes** [comment]
65de7263f222014d8a4595bcf5525abc458df411 calm down next time
