### ISSUE TITLE
priority for autototem

### ISSUE THREAD

**Issue by v4ne4ka** [ionar2/salhack#212]
**Is your feature request related to a problem? Please describe.**
No, autototem has bugs but this suggestion is not about it

**Describe the solution you'd like**
Make priority for AutoTotem switchable between inventory and hotbar

**Describe alternatives you've considered**
idk 

**Additional context**
Just make old autototem priority as switchable mode please

**Comment by Tyler2b2t** [comment]
yeah idk why you guys started prioritizing the hotbar just because one idiot told you to. He has no idea how to pvp

**Comment by very-cashmoney** [comment]
its already reported + wrong label

**Comment by very-cashmoney** [comment]
#199
