### ISSUE TITLE
optifine breaks ESP

### ISSUE THREAD

**Issue by Manaball123** [ionar2/salhack#214]
**Describe the bug**
all of the ESP(EG:crystal placement indicator, holeESP etc.)will turn gray if optifine is used

**To Reproduce**
1. put optifine in mods
2. launch minecraft
3. enter any world and turn on any ESP

**Expected behavior**
the ESP color should be normal

**Comment by very-cashmoney** [comment]
not an optifine issue.

**Comment by ionar2** [comment]
Have you tried the latest release?

**Comment by impulsivus** [comment]
Works fine.
