### ISSUE TITLE
No crystal pickaxe hit

### ISSUE THREAD

**Issue by TheAdiCt3dkid** [ionar2/salhack#223]
Like already mentioned I like to faceplace people while breaking their suround.
This one may be a bit hard to code but itz really usefull if it works.
Implement a module that doesn t  let you break crystals with pickaxe but mine block
Ur looking at.
This would alsow have to work with crystalaura so you can still break blocks with ca while having a pickaxe in your hand. 

I hope you can code that one and that I could explain my idea.
Hope to see it in one of the next releases.

**Comment by very-cashmoney** [comment]
there is alreade a module bruh
