### ISSUE TITLE
CA rewrite detonates manually placed crystals even if theres no enemies around

### ISSUE THREAD

**Issue by EmrysLe** [ionar2/salhack#229]
**Describe the bug**
CA rewrite detonates manually placed crystals even if there's no enemies around.
**To Reproduce**
1. Turn off CA rewrite
2. Place a crystal with no one else nearby
3. Turn on CA rewrite
4. Watch CA rewrite detonate crystal even if no one is nearby

**Expected behavior**
CA should not detonate crystals when there's no enemies around, and conditions are clearly not met

**Screenshots**

**Additional context**

**Comment by very-cashmoney** [comment]
not a bug, change the destroymode to Smart; And close this thread

**Comment by Flika1999** [comment]
There are many reasons detonating without enemies is useful.  Better to leave it this way
