### ISSUE TITLE
Console command "unbind" binds the module to alt.

### ISSUE THREAD

**Issue by Han75** [ionar2/salhack#23]
**Describe the bug**
Tiitle. I type unbind and it binds the hack to left alt.
**To Reproduce**
1. Go to 'console'
2. Type 'unbind [I used scaffold so scaffold]
3. Press left alt.

**Comment by dominikaaaa** [comment]
This is most likely due to the "fix" for #8

**Comment by ionar2** [comment]
Can't reproduce
