### ISSUE TITLE
Crash with Impact + salhack

### ISSUE THREAD

**Issue by uAliFurkanY** [ionar2/salhack#231]
**Describe the bug**
Salhack crashes when joining a server.

**To Reproduce**
1. Use impact + salhack
2. join server
3. See error

**Expected behavior**
It should work

**Screenshots**
![this](https://user-images.githubusercontent.com/57134217/82906468-f8a47300-9f6d-11ea-9998-f1d420f94f62.png)

**Additional context**
Using it with Impact, also latest release caused it.

**Comment by dominikaaaa** [comment]
provide a log
