### ISSUE TITLE
Search gui

### ISSUE THREAD

**Issue by thetaxitank** [ionar2/salhack#248]
**Is your feature request related to a problem? Please describe.**
Yeah in fact I have found myself getting a bit overwhelmed by the gui.... with this ammount of modules I get a bit confused. ._.

**Describe the solution you'd like**
I dont really want any specific type of gui... just would like it to be comfortable to use. Say for example, Ares and Wurst got nice guis. You think that making something of that sort is possible? 
:)

**Describe alternatives you've considered**
As I have already mentioned, Ares or Wurst type gui; or alternatively making the module's "subsettings" appear horizontally instead of vertically.

**Additional context**
![image](https://user-images.githubusercontent.com/62184311/83178099-b30ab600-a0e5-11ea-886a-2856350bd045.png)
![image](https://user-images.githubusercontent.com/62184311/83178188-cf0e5780-a0e5-11ea-9efa-3ae4c978c604.png)

its up to you if u wanna do it or not... :3

**Comment by dominikaaaa** [comment]
#183
