### ISSUE TITLE
Suggestion: An option to disable auto switch in ca

### ISSUE THREAD

**Issue by lorem-impsum** [ionar2/salhack#25]
An option to disable auto switch in auto crystal would be useful.

**Comment by ionar2** [comment]
So it should not place when you don't have a crystal in your hand, but stillbreak?

**Comment by dominikaaaa** [comment]
I think they mean automatically switching to the item to place, so yea. Both placing and breaking can be optional.

**Comment by lorem-impsum** [comment]
Yes. If auto switch is off, it wouldn't switch to the crystals automatically, but it would still place them if you switched to crystals manually. Wether it breaks crystals or not would be determined by your break mode. So if it's on always then it would still try to break the crystals around you with the item you have in your hand. And for example if it's on only own it would only break crystals that that was placed by it when you had crystals in your hand. (or was placed by the player)

**Comment by ionar2** [comment]
new option OnlyPlaceWithCrystal will be implemented
