### ISSUE TITLE
Salhack has yee'd its last haw

### ISSUE THREAD

**Issue by iBuyMountainDew** [ionar2/salhack#259]
kinda sad tbh, ionar was essentially forced into open source (which he really didn't want, cos he would end up receiving few contributions and TONNES of requests) and on top of irl issues, it's safe to say that the salhack days are done.

:crab:

**Comment by dominikaaaa** [comment]
to add to this, I'm supposed to maintain this project, and the only person with a higher ranking role (jumping) banned me from the discord for some reason.

**Comment by dominikaaaa** [comment]
¯\_(ツ)_/¯
