### ISSUE TITLE
Auto surround

### ISSUE THREAD

**Issue by lorem-impsum** [ionar2/salhack#26]
A module that would automatically enable surround if you are in an obsidian hole. Would only enable it once so the surround could be turned off without having to turn off the auto surround module.

**Comment by dominikaaaa** [comment]
No.

**Comment by lorem-impsum** [comment]
bruh

**Comment by lorem-impsum** [comment]
♿

**Comment by dominikaaaa** [comment]
# ♿♿♿

**Comment by ionar2** [comment]
Don't rely on surround. This is a user issue not a client issue.
