### ISSUE TITLE
GUI off screen and Larger Cheat Menu

### ISSUE THREAD

**Issue by Dyllpyckyll** [ionar2/salhack#262]
The bug will make the icons for the cheat menus such as "Render" much larger then normal. This makes some menus go off screen and the HUD is completely gone for salhack. The HUD that contains coordinates, the armor I am wearing, and more. This makes it hard to navigate around actually use this hack engine.

I have not figured out how to undo this bug but it has been like this since I have had salhack.

**Expected behavior**
I expected the hack to operate normally and have the normal sized icons and have the HUD showing.

**Screenshots**
![2020-05-30_14 04 06](https://user-images.githubusercontent.com/61995054/83337027-087dc900-a286-11ea-98b3-950bb02c97b3.png)

**Additional context**
N/A

**Comment by Jumpinqq** [comment]
Minecraft > Options > Video Settings > GUI Scaling: Normal.

**Comment by dominikaaaa** [comment]
Why not actually fix the bug?
