### ISSUE TITLE
Make Backspace Delete Keybinds

### ISSUE THREAD

**Issue by Jumpinqq** [ionar2/salhack#28]
I can't delete keybinds afaik, so making the DELETE key or the BACKSPACE key do that would be useful.

Edit: just realized unbind is a thing in the console

**Comment by lorem-impsum** [comment]
You can. Middle click the keybind option in the click gui to delete the keybind. Or you can just use the console and write in bind <module-name> none.

**Comment by dominikaaaa** [comment]
Would still be nice to have delete do it as well.

**Comment by dominikaaaa** [comment]
There's no need to close this?
