### ISSUE TITLE
White screen when I die/teleport

### ISSUE THREAD

**Issue by noTosalphA** [ionar2/salhack#281]
Whenever I die my game screen turns white. This also happens when I teleport too. I use WWE and SalHack, they are usually fine until I die or teleport, and when I do the screen turns white/bright colors and I can't see anything. I can still interact with the environment but I have to alt+f4 to see anything.

To reproduce, just have SalHack and WWE. I'm not sure if it's a comparability issue or a bug with the two clients. It happens with none of the options on

**Comment by noTosalphA** [comment]
Apparently the buy was caused by no fog being on

**Comment by Vaixe24Alt** [comment]
Yeah that is just a nofog issue, will get round to making a toggle for nofog to turn off when respawning. @noTosalphA close this for now
