### ISSUE TITLE
Blur-Mod Doesn't work with OptiFine

### ISSUE THREAD

**Issue by DeletedUser0000** [ionar2/salhack#29]
While using OptiFine the blur mod doesn't work correctly.

1. Put OptiFine 1.12.2 in your mods folder
2. Put the Blur mod in your mods folder
3. Start minecraft & load into a world
4. Open any GUI
The blur won't work for whatever reason.

I tried this without removing any mods other than optifine and the blur worked perfectly.

**Comment by ionar2** [comment]
Until this mod is fully incorporated in this repo itself, this is a wontfix
