### ISSUE TITLE
A Few Suggestions & Improvements

### ISSUE THREAD

**Issue by fr0zenbyte** [ionar2/salhack#3]
Color Options for more modules (esp inventory preview armor preview etc)
Chat Toggle Messages (tells you when you turn on/off crystal aura or surround)
Hole Mining Notifications (player is mining blocks near you in chat or something)
Make AutoArmorMend cancel if you start moving (sometimes it gets stuck for me)
Logout Spots (with current player health and armor dura)
Alerts if your armor dura is under X amount 
Anti Chain Pop (disable CA and toggle surround if you pop more than 2 times)

**Comment by dominikaaaa** [comment]
Please open separate issues for separate suggestions, and use the issue template.
