### ISSUE TITLE
CityESP and AutoCity

### ISSUE THREAD

**Issue by myheartwentok** [ionar2/salhack#33]
Often it can be hard to tell wether you are able to citytrap someone from the angle where you are standing, and going into freecam to a. see if it is feasable and b. mine the block is arduous. Or, you need to relocate just for the purpose of mining that block, which will often broadcast to the user your intentions.

CityESP: renders an esp over a block that if mined, would citytrap the oponent. This feature exists already in veteranhack so feel free to look there to see what an implementation looks like.

AutoCity: When toggled, if a CityESP is present, mines the block with the esp on it.

**Comment by ionar2** [comment]
This might not get done for a few days.

**Comment by pol-y-mer** [comment]
ionar, i can give you the code for this! i wrote it for vethack. Id be happy to work together on this if you have any suggestions for me!

**Comment by ionar2** [comment]
Create a PR and I will review it @pol-y-mer

**Comment by ionar2** [comment]
Does NCP flag you if you try to mine a block out of line of sight? I know you are able to place like that.
