### ISSUE TITLE
AutoDelay for Crystal Aura

### ISSUE THREAD

**Issue by myheartwentok** [ionar2/salhack#37]
Sometimes my ping changes and my hit delay settings for crystal aura are no longer optimal. It would be helpful if the CA had an option that calculated the optimum delay for you. The maths looks like this:
Delay = 2*ping*(tps/20)+(ping/10)

thanks

**Comment by Jumpinqq** [comment]
I'm not 100% sure but I think your math is incorrect. I ran the math with a ping of 12 and tps of 14 and I got a delay of 18. Normally I use 2. Is there something I'm missing?

**Comment by myheartwentok** [comment]
It might be your units. These are the units I intended
Delay in ms
ping in ms
I dont know how the salhack delay value overlays to the ms delay

**Comment by Jumpinqq** [comment]
oh yep, thats probably why.

**Comment by ionar2** [comment]
There are 40 ticks per second on the tick event. AutoCrystal uses the tick event, and NCP bypasses at a tick delay of 2

Can you incorporate your formula to use ticks instead of ms delay?

**Comment by ionar2** [comment]
Also I think this is invalid/unneeded because mine queues packets rather than editing existing ones. Going to close this, make a new issue with proper information.
