### ISSUE TITLE
ExtraTab does not work 

### ISSUE THREAD

**Issue by FlytoNorway** [ionar2/salhack#41]
ExtraTab does not work when salhack is included in the mods folder, when i drag salhack out of it ExtraTab works as it should. this was an issue with kami blue before, but it works now. if you could try fix this or either ask how bella did it then that would help.

**Comment by dominikaaaa** [comment]
Mixin probably incompatible with another mod.

**Comment by ionar2** [comment]
Move the slider up under Hud, there's a slider for extratab
