### ISSUE TITLE
Automend having antisuicide

### ISSUE THREAD

**Issue by Rodan427** [ionar2/salhack#43]
Make an option so that if a crystal is right in front of you while you have automend on it gets disabled.

**Comment by ionar2** [comment]
You can toggle off automend armor manually with autoarmor enabled, should this really be an option? seems like it would cause more annoyance than usability.

**Comment by Rodan427** [comment]
Well it would probably be better to have it get disabled if the crystal explodes in front of you

**Comment by dominikaaaa** [comment]
Instead of disabling, you could just not right click if looking at a crystal

**Comment by ionar2** [comment]
How should it work then, if there exists a crystal within 5 yards infront of you toggle? Seems pretty stupid

**Comment by dominikaaaa** [comment]
If they're looking at a crystal, I think. 

But automend right clicks and you need to left click to break a crystal.
