### ISSUE TITLE
A new idea for NoRender

### ISSUE THREAD

**Issue by NekoPvP** [ionar2/salhack#44]
Maybe add NoArmor to NoRender. It doesnt render ur armor when you wear it. Maybe a nice feature? Maybe not? id like it if it is possible!

**Comment by ionar2** [comment]
I will look into it

**Comment by dominikaaaa** [comment]
KAMI Blue has this :+1:

**Comment by ionar2** [comment]
61663f4081aeb0d1beca5268b67d1882b3a03eb5
