### ISSUE TITLE
Could you add a presets tab like in wwe so I can quickly change settings for different servers

### ISSUE THREAD

**Issue by Gopro336** [ionar2/salhack#50]
Could you add a presets tab like in wwe so I can quickly change settings for different servers

**Comment by ionar2** [comment]
How does it work in WWE client? Does it allow you to create and save all module settings/keybinds as a preset, then load it on demand?

**Comment by dominikaaaa** [comment]
Yes.

**Comment by lorem-impsum** [comment]
Seems like a great idea.
