### ISSUE TITLE
Auto crystal bot MIA (seen on ihackedxvideo's youtube)

### ISSUE THREAD

**Issue by Gopro336** [ionar2/salhack#53]
before salhack was public I saw a video on Ihackedxvideos channel and in it, the click GUI had a feature under the bot dropdown named "auto crystal bot" It is missing in the current release

**Comment by dominikaaaa** [comment]
Enable autocrystal.

**Comment by ionar2** [comment]
Was never finished, or added in rewrite, this is why the values are static in autocrystal mod.

WontFix
