### ISSUE TITLE
Console enhancement

### ISSUE THREAD

**Issue by brixalis** [ionar2/salhack#55]
I think console should be changed to ".chat"
or clicking . opens console and console working like chat but separate.
Also if this is added put an option to change the prefix so it would be compatible with other clients

**Comment by dominikaaaa** [comment]
You can change the prefix.

**Comment by ionar2** [comment]
We actually don't use chat commands @dominikaaaa but a console gui.

Also @brixalis I don't understand your issue, how should it function instead?
