### ISSUE TITLE
Add Auto Nametag module

### ISSUE THREAD

**Issue by brixalis** [ionar2/salhack#56]
Make a module that makes you rename the entities depending on the range.
This could be useful with AutoWithers, whenever you placed a Wither it would rename it automatically

**Comment by ionar2** [comment]
How should it work?

Should options go as follows?:

Mode: <AllNameableEntities> <Withers> <Animals> <Mobs>
Boolean: ReplaceOldNames
Boolean: AutoSwitch

Then should it only function if nametag is in main hand?
