### ISSUE TITLE
AutoMultiplace for autocrystal

### ISSUE THREAD

**Issue by p92q** [ionar2/salhack#58]
it would be cool to have an option where it automatically toggles multiplace when a person is running from you, then when they are out of reach it gets untoggled

**Comment by ionar2** [comment]
How should we determine when a person is running from you? Should it work when their 2d distance exceeds 3 and is not less than 6?

**Comment by lorem-impsum** [comment]
Seems complicated and kinda pointless.

**Comment by p92q** [comment]
Well it would be better to have a thing were multiplace gets toggled if they are at a certain health, kinda like faceplacing

**Comment by ionar2** [comment]
Now that's a better suggestion.

So new options 

"AutoMultiplace" <boolean>
"HealthBelowAutoMultiplace" <float> - If targets health is below this value, automatically enable multiplace.

Does that sound good?

**Comment by p92q** [comment]
Yes
