### ISSUE TITLE
Crash bug in servers when i use /kit

### ISSUE THREAD

**Issue by Disu123** [ionar2/salhack#59]
When i use /kit on a cpvp server

1. Go to 'the server'
2. Put "/pvpkit"
3. And crash

I think is for the fast is the auto totem and the auto armor

Screenshots
![error](https://user-images.githubusercontent.com/64975933/81319287-d5209380-9065-11ea-8dc5-775326835d80.png)

i dont know if is salc1 or the server,but when i use another clients that doesn't happen

**Comment by dominikaaaa** [comment]
Send the crash log.

**Comment by Disu123** [comment]
[crash-2020-05-07_13.18.32-client.txt](https://github.com/ionar2/salhack/files/4594299/crash-2020-05-07_13.18.32-client.txt)

**Comment by lorem-impsum** [comment]
Happened to me before, turning of container preview fixed it.

**Comment by Disu123** [comment]
> Happened to me before, turning off container preview fixed it.

Thx, now i dont get crash
