### ISSUE TITLE
maybe can you make the offhand gap and offhand crystal different mods? its will be helpful

### ISSUE THREAD

**Issue by afikonda** [ionar2/salhack#6]
maybe can you make the offhand gap and offhand crystal different mods? its will be helpful

**Comment by ionar2** [comment]
Why? it's automatic in autototem, you will soon be able to bind keys to switch modes on demand, no reason to clutter client with these kind of mods

**Comment by v4ne4ka** [comment]
Agree! Sometimes AutoTotem swtiches gapple while eating it because of low health, it is really annoying
