### ISSUE TITLE
How do i build this?

### ISSUE THREAD

**Issue by DiamondMiner88** [ionar2/salhack#73]
I tried doing `gradlew.bat build` and then tried both jars in /build/libs/ in a custom version but they both crashed.
I haven't built jars for using gradle before. How do i do it?

**Comment by dominikaaaa** [comment]
You need to use the -release jar. If you get a crash using it, post the log.

**Comment by DiamondMiner88** [comment]
Just to verify i copied 1.12.2's json file is that right?
I just tried the -release jar and it still crashed, no logs

**Comment by dominikaaaa** [comment]
No? You're not doing anything with jsons. And it's impossible to get no logs except for a few very specific circumstances which don't apply to you.

**Comment by dominikaaaa** [comment]
I just built it myself like 20 seconds ago, and it works. 
![2020-05-08-205910_1920x1080_scrot](https://user-images.githubusercontent.com/17222512/81459595-c671d380-916e-11ea-8969-e65c6fb9bfd0.png)

**Comment by DiamondMiner88** [comment]
oh i didnt realize it was a forge mod whoops

**Comment by dominikaaaa** [comment]
massive brain

# :monkey:

**Comment by dominikaaaa** [comment]
It's against mojang's ELUA to distribute Minecraft code, I don't know where you got the idea of replacing Minecraft's jar with this, especially if this is on gihtub o_O
