### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by turtleog** [ionar2/salhack#75]
Can you consider the following features
Text Radar
Steal / store buttons on chest
auto eat
avoid/ignore- avoid flys away from people while elytra flying example- hovering over 00 if someone comes withen a certain distance with you it would move away if afk. And ignore would be the opposite and follow them.
Torch placer places torches in areas below light level 7

**Comment by NV-Performance** [comment]
pls make sth like block highlight that make the outline bigger. And u can customise the color.

**Comment by dominikaaaa** [comment]
Open separate suggestions in separate issues.
