### ISSUE TITLE
Issue with faceplace 

### ISSUE THREAD

**Issue by dermono** [ionar2/salhack#78]
I noticed that if someone dips below the health I have set for faceplace, then goes above it, the faceplace will continue spamming crystals at them, even if they have high health.

**Comment by Jumpinqq** [comment]
can confirm

**Comment by ionar2** [comment]
Self reference: https://github.com/ionar2/salhack/blob/master/src/main/java/me/ionar/salhack/module/combat/AutoCrystalModule.java#L719 Might need to add absorption to health to fix this

**Comment by dermono** [comment]
> Self reference: https://github.com/ionar2/salhack/blob/master/src/main/java/me/ionar/salhack/module/combat/AutoCrystalModule.java#L719 Might need to add absorption to health to fix this

How about adding absorption to autototem as well? (for offhand)

**Comment by ionar2** [comment]
That belongs in a separate issue.
