### ISSUE TITLE
pressing the unmute button on my keyboard toggles on every module at the exact same time

### ISSUE THREAD

**Issue by Robert5204** [ionar2/salhack#8]
what the fuck please help

**Comment by Artamedes** [comment]
what key is that?

**Comment by dominikaaaa** [comment]
what is it

**Comment by Robert5204** [comment]
> what key is that?

the mute/unmute button on my keyboard
ignore the shit on it its my great uncles daughters nephews keyboard they gave it to me
![unnamed](https://user-images.githubusercontent.com/20491428/81028937-42a7a680-8e51-11ea-99f7-b3abb6e150e6.jpg)

**Comment by Robert5204** [comment]
btw it only happens when unmuting, muting is fine.

**Comment by dominikaaaa** [comment]
bruh what 

i mean that's probably your computer's fault

**Comment by Robert5204** [comment]
so you're telling me that my computer manages to toggle on every module in salhack at the exact same time whenever i unmute it

**Comment by Robert5204** [comment]
ill record a video of it in action if i can get my minecraft to not die hold on

**Comment by Lendud** [comment]
bro clean ur mf keyboard

**Comment by Robert5204** [comment]
no

**Comment by Robert5204** [comment]
ok we have a new development now just muting my computer does it too

**Comment by Robert5204** [comment]
video is almost finished rendering good thing i bought a gtx 1080 ti

**Comment by Robert5204** [comment]
ok here is the promised video
https://cdn.discordapp.com/attachments/626066604589056031/707050829298925698/IMG_1278.MOV

**Comment by chewibles** [comment]
wtf look at this fools keyboard LMAOOOOO

**Comment by Robert5204** [comment]
shut the heck up buddy >:(

**Comment by Robert5204** [comment]
on a side note it has came to my attention that ruhama actually had this issue too. maybe go ask him how he fixed it 😳

**Comment by DualizedRain** [comment]
had this same issue when playing on a server it pretty much lagged my  client out

**Comment by cookiedragon234** [comment]
It’s caused by clients using NONE key to represent a bind not existing. Because your volume up key is not a key represented by lwjgl it defaults back to NONE key, which is technically bound to all your modules. The way to fix this is to not perform keybind checks if the keybind is NONE.

**Comment by cookiedragon234** [comment]
And it’s not “your computer's fault”, it’s because the devs skidded kami and don’t even know their own code base

**Comment by Robert5204** [comment]
arent u the guy that backdoored ur own client 😳

**Comment by dominikaaaa** [comment]
@cookiedragon234 then that literally does mean it is their computers fault, as for some reason their computers keyboard thinks volume key = none key

If it was common or good practice to do that to your keyboard, I would've had someone report this bug in kami, as it has thousands of users.

**Comment by babbaj** [comment]
![image](https://user-images.githubusercontent.com/12820770/81132980-3d645d80-8f1e-11ea-9f6d-96925e4ae7cd.png)
vanilla doesn't have this problem 🤡

**Comment by dominikaaaa** [comment]
neither does kami. I don't know what ionar did wrong lol. having it equal to 0 is normal for "hey, there's not key for this"

**Comment by ionar2** [comment]
it's already fixed, i only checked for null or empty, either way it was simple as reproducing and seeing the callstack and key == "NONE"

**Comment by cookiedragon234** [comment]
> @cookiedragon234 then that literally does mean it is their computers fault, as for some reason their computers keyboard thinks volume key = none key
> 
> 
> 
> If it was common or good practice to do that to your keyboard, I would've had someone report this bug in kami, as it has thousands of users. 

It’s not “the computers fault”. Which key in Keyboard class do you think lwjgl should return if you press a volume key? Hint: there is no key for the volume button, therefore the only choice is NONE. It’s the programmers fault for deciding that it is valid to trigger the keybind with a key of NONE.
