### ISSUE TITLE
Make smart explode actually smart

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#81]
I think the _ideal_ smart explode should check to see if exploding the crystal will do >= the min damage before every time it tries to explode a crystal. I think the smart mode atm only checks to see if exploding the crystal will do below max self-damage. I think this would improve crystalling people while chasing them as itd reduce your chance of selfpopping or hitting crystals that wont do anything.  A feature like this might not be important to players with super low ping because the place damage calculation does a good enough job as they'll just explode the crystal instantly. This would more or less benefit people with 150+ms id imagine.

**Comment by ionar2** [comment]
Right now the AutoCrystal is only checking if damage done to target > 0 and if damage done to self is below maxselfdamage 

`
                float l_TargetDMG = CrystalUtils.calculateDamage(mc.world, p_Entity.posX + 0.5, p_Entity.posY + 1.0, p_Entity.posZ + 0.5, l_Target, 0);
                float l_SelfDMG = CrystalUtils.calculateDamage(mc.world, p_Entity.posX + 0.5, p_Entity.posY + 1.0, p_Entity.posZ + 0.5, mc.player, 0);
                
                if (l_TargetDMG > 0 && l_SelfDMG < MaxSelfDMG.getValue())
                    return true;
                
`

So as far as I understand to improve it, instead of a > 0 here, it should be mindmg, unless face placing is available?

**Comment by r-33** [comment]
Yes I think that would be more effective . I dont think it actually works as is "Right now the AutoCrystal is only checking if damage done to target > 0 and if damage done to self is below maxselfdamage". I was testing it in-game and it would explode the crystal even if no one was around. I also just realised this "smart explode" would also be good for not exploding crystals while travelling on a highway with ca turned on. Im sure everybodies accidently popped a totem like this.
