### ISSUE TITLE
Flatten - Autobuild issues

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#83]
Flatten doesnt really work unless youre on bedrock as it tries to place blocks in thin air. If it was designed to place blocks off existing blocks instead of thin air it would be way more multipurpose. I guess it could be used quickly build parts of a floor in a house or something like that.

**Comment by ionar2** [comment]
I don't quite understand what you want it to accomplish, it automatically already does build a floor, as long as your standing on 1 block below you.

**Comment by ionar2** [comment]
Closed because op had wrong settings, must use blockspertick 1
