### ISSUE TITLE
Auto Armour on hold

### ISSUE THREAD

**Issue by Lendud** [ionar2/salhack#84]
I think it would be a good idea to make an option for auto armour that allows it to only replace armour when held. This could be useful when you're trying to automend and all your armour is scattered so you just hold down the autoarmour until your armour equips.

**Comment by ionar2** [comment]
This seems useless, automend pauses autoarmor by default anyway.

**Comment by Lendud** [comment]
Didn't know that automend paused autoarmor, thanks though for your response. ♿
