### ISSUE TITLE
Quiver Module

### ISSUE THREAD

**Issue by Tyler2b2t** [ionar2/salhack#85]
I am new to pvp and I noticed people using different types of arrows in combat. However, it seems switching between arrows takes too long.

A solution I thought of would be to have arrows in the xcarry, and then binds for each xcarry slot: 1,2,3,4, for example. The bind would swap whatever arrows are in the player inventory with the items in the bound xcarry slot. 

The above solution would swaps the items directly, so the arrows in the player inventory would now be in the bound xcarry slot, putting it upon the player to keep track of which items are in which xcarry slot at all times. Another solution would be to keep the xcarry slots fixed. In this case, only 3 xcarry slots would ever be full at any given time. For example, 1 would be bound to the upper-left xcarry slot containing strength II arrows, and the bottom-right xcarry slot remains empty. If the player presses 1, a single stack of arrows is sent the bottom right slot if possible, and then the strength II arrows from the 1 slot could be moved into the inventory. When another xcarry bind is pressed, like 2, the strength arrows are moved back to the upper-left slot bound to 1, so the same type of arrow is always bound to the same key. This could be extended to work for other things besides arrows too, maybe even the notool could work with xcarry.

![2020-05-10_10 12 42](https://user-images.githubusercontent.com/64818576/81506124-050ba900-92a9-11ea-9b97-77638cbf3ad8.png)

**Comment by dominikaaaa** [comment]
This isn't possible due to the issue described here: https://github.com/kami-blue/client/issues/639
