### ISSUE TITLE
NoMiningTrace No Longer Works

### ISSUE THREAD

**Issue by Jumpinqq** [ionar2/salhack#89]
Not sure what happened, but the module NoMiningTrace no longer has any effect after I installed the latest update. It could just be me though. 

Expected behavior:
- Be able to mine through entitys while holding a pickaxe

Additional context:
It's now as if the module isn't even on

**Comment by dominikaaaa** [comment]
What server/

**Comment by dominikaaaa** [comment]
The NoMiningTrace module hasn't ever been updated since SalHack went public

**Comment by ionar2** [comment]
Can't reproduce in latest, try using a later build
