### ISSUE TITLE
Presets for auto crystal 

### ISSUE THREAD

**Issue by Bubba112** [ionar2/salhack#91]
For when your pvping on different servers like 2b and 2bpvp are very different

**Comment by r-33** [comment]
would these be premade presets made by ionar with different playstyles or different ca configs you make yourself and can swap on the fly?

**Comment by ionar2** [comment]
Seems worse idea or duplicate of #50

**Comment by dominikaaaa** [comment]
I don't understand why people can't make their own configurations and rely on others to make them. Just play the game for gods sake
