### ISSUE TITLE
Packet Anti-AFK or working 2b AntiAfk

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#92]
Ive heard that a few private clients have a working 2b anti afk by sending packets to the server to I guess to spoof movement and so on. Something like this or a working 2b antiafk would be nice. (I tested the current one on 2b2t multiple times and got kicked. I dont know how typing /stats would prevent anti afk but it doesnt seem to work (at least from my testing))

_Not sure if this is supposed to go under the bug category or new module cos it's kinda both._

**Comment by dominikaaaa** [comment]
That's not possible. 2b2t's afk kicks you if you stay within couple of chunks. You have to move between 3 different chunks iirc

**Comment by r-33** [comment]
bruh why is this closed "or working 2b AntiAfk" 
also that isn't true. You can be kicked for flying afk after a bit unless you punch a block or do an action like eat a gapple.

**Comment by dominikaaaa** [comment]
I didn't say that moving between different chunks was the **only** requirement.
