### ISSUE TITLE
Anti Elytra Fly crash

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#94]
concept: A little toggleable button under the elytra fly gui that stops you before you crash into anything to the sides, in front, or on top of the user. (while flying obviously)
reason: It kinda sucks crashing into something on a highway and taking damage or having to take off again, also sometimes you get kicked if you keep flying into a wall (which can happen when you're afk a lot)
Is this necessary? No, but I don't see why a user wouldn't like this nor find an application for it in everyday use. However, even though it sounds simple in concept id imagine it would be pretty hard to make. However x2, this would be a one of a kind feature to my knowledge

**Comment by dominikaaaa** [comment]
This isn't possible due to the processing power ray tracing at elytraflight speeds would take tbh
