### ISSUE TITLE
Crashes when using it with impact

### ISSUE THREAD

**Issue by lorem-impsum** [ionar2/salhack#96]
This error only occurred in the latest version. The game simply crashes when you try to play on a server. The crash report: https://pastebin.com/caA6Dev7

**Comment by lorem-impsum** [comment]
Oh wait I forgot to add incompatibility tag.

**Comment by dominikaaaa** [comment]
![](https://cdn.discordapp.com/attachments/573955213879410689/710157882196361276/Screenshot_20200513-115319.png)

**Comment by impulsivus** [comment]
May I ask what exactly is the "temporary" fix? I have modified `mcmod.info` file like this:
`
  "dependencies": ["required-after:impact"]`

Had no luck.

**Comment by dominikaaaa** [comment]
You rename the file itself. you don't mess with mcmod.info or whatever, as you can see in my screenshot

**Comment by impulsivus** [comment]
> You rename the file itself. you don't mess with mcmod.info or whatever, as you can see in my screenshot

Also tried that but did not work. I added "a" to the beginning of impact and salhack at different instances, crashed every time.

**Comment by dominikaaaa** [comment]
they have to be in the same folder as well

**Comment by impulsivus** [comment]
> they have to be in the same folder as well

Still crashing.

**Comment by lorem-impsum** [comment]
It works fine for me now.

**Comment by dominikaaaa** [comment]
¯\\\_(ツ)_/¯

**Comment by impulsivus** [comment]
> It works fine for me now.

Can you send a Screenshot of what you have done?

**Comment by lorem-impsum** [comment]
> > It works fine for me now.
> 
> Can you send a Screenshot of what you have done?

I can't, I'm not home but basically what I did is that I renamed salhack to the letter "a" and left impact as it is both in the mods folder not in a sub-folder of that. Also, use the latest version of salhack.

**Comment by impulsivus** [comment]
I noticed that the latest GITHUB release of salhack works with Impact, I renamed impact to AImpact and it worked. The one I built at my own PC did not work, interestingly. 
Sent from Outlook Mobile



On Sat, May 16, 2020 at 10:04 AM +0300, "lorem-impsum" <notifications@github.com> wrote:

















It works fine for me now.



Can you send a Screenshot of what you have done?



I can't, I'm not home but basically what I did is that I renamed salhack to the letter "a" and left impact as it is both in the mods folder not in a sub-folder of that. Also, use the latest version of salhack.

**Comment by ionar2** [comment]
Can this be closed now? Impact support should be fixed.

**Comment by lorem-impsum** [comment]
I guess it is. I had no issues since the 3rd latest update.
