### ISSUE TITLE
Better Offhand

### ISSUE THREAD

**Issue by r-33** [ionar2/salhack#99]
Theres been a lot of people who think the sword offhand gap is too different to the usual toggle to get offhand

Concept: Keep fallback mode on autototem but have a separate module which allows the user on trigger to select between a gapple, crystal, sword or bow in their offhand instead of the totem. Also a safety mechanism that lets the user set a desired health and if their health reaches below that the module turns itself off back to a totem.

**Comment by v4ne4ka** [comment]
Yeah! It would be great, kami blue has similar function but it has crashes so nah i really want it in SalHack, maybe it wont crash there

**Comment by dominikaaaa** [comment]
If it has a crash you can make a bug report, I can't fix anything I'm unaware of.

**Comment by dominikaaaa** [comment]
Also, I'm 99% sure I fixed the crash bug in the latest beta

**Comment by ionar2** [comment]
Report kami blue bugs on their issue tracker here: https://github.com/kami-blue/client/issues

On topic: I will try and do this tonight.

**Comment by v4ne4ka** [comment]
> If it has a crash you can make a bug report, I can't fix anything I'm unaware of.

someont has already reported it, and its not fixed

**Comment by dominikaaaa** [comment]
There's an opened crash report for something unrelated. There used to be an offhandgap crash which was fixed a while ago.
